"""empty message

Revision ID: 2674a3f8af31
Revises: 3adbe8a9ca37
Create Date: 2023-03-02 22:28:55.785805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2674a3f8af31'
down_revision = '3adbe8a9ca37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('root_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'comment', ['root_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('root_id')

    # ### end Alembic commands ###
