"""empty message

Revision ID: 2fbf1ac8d1b5
Revises: 5a0d843ef718
Create Date: 2023-03-01 22:57:19.883885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2fbf1ac8d1b5'
down_revision = '5a0d843ef718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('body', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'admin', ['author_id'], ['id'])
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('body')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
