"""empty message

Revision ID: f84c0ee08a54
Revises: 2674a3f8af31
Create Date: 2023-03-06 15:13:52.522940

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f84c0ee08a54'
down_revision = '2674a3f8af31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('article_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'admin', ['creator_id'], ['id'])
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('article_ibfk_1', 'admin', ['author_id'], ['id'])
        batch_op.drop_column('creator_id')

    # ### end Alembic commands ###
